### ISSUE TITLE
블루투스 값 넘겨줄 때 치아 번호 이외의 번호 전송받음

### ISSUE THREAD

**Issue by yuseon27** [Team-Achi/Android#5]

**Comment by yuseon27** [comment]
왼쪽 위아래만 값 넘겨주는데 55.66,77 등의 숫자가 전달됨

**Comment by yuseon27** [comment]
그 외 이상한 문자도 전달됨. ex) ���11

**Comment by suzennk** [comment]
왼ㅉ 뭔가요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by suzennk** [comment]
8ec91a2a580cb711e0704470b51bbd0001c66ae2
